[package]
name = "introcg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "0.120.0"
image = "0.23.14"
rand = "0.8.4"
rayon = "1.5.1"
bvh = "0.6.0"
